"""add mpesa_code to expenses and incomes

Revision ID: 2a56ee06bcd3
Revises: 244d8b4e4a45
Create Date: 2026-09-03 20:33:41.764046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a56ee06bcd3'
down_revision = '244d8b4e4a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_code', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_expense_user_mpesa_code', ['user_id', 'mpesa_code'])

    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_code', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_income_user_mpesa_code', ['user_id', 'mpesa_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_income_user_mpesa_code', type_='unique')
        batch_op.drop_column('mpesa_code')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('uq_expense_user_mpesa_code', type_='unique')
        batch_op.drop_column('mpesa_code')

    # ### end Alembic commands ###
